// Stub for testing — real server.ts is generated by `npx convex dev`
// Re-exports the generic builders from convex/server that work without generated code.
export {
  queryGeneric as query,
  mutationGeneric as mutation,
  actionGeneric as action,
  httpActionGeneric as httpAction,
} from "convex/server";
